config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  root to: "homes#top"
  resources :users,only:[:show,:edit,:update]
  resources :lists,only:[:index,:create,:destroy]
  resources :tasks,only:[:create,:edit,:update,:destroy]
  resources :challenges,only:[:index,:create,:destroy]
  resources :rewards,only:[:create,:update,:destroy]
  
  patch '/users/:id/withdrawal' => 'users#withdrawal',as:'withdrawal_user'
  
  get '/list' => 'lists#new',as:'new_list'
  
  get '/task/calendar' => 'tasks#calendar',as:'calendar_task'
  get '/task' => 'tasks#new',as:'new_task'
  get '/tasks/:id' => 'tasks#index',as:'index_tasks'
  patch '/complete_all_tasks/:id' => 'tasks#complete_all',as:'complete_all_task'
  patch '/complete_tasks/:id' => 'tasks#complete',as:'complete_task'
  delete '/destroy_all_tasks/:id' => 'tasks#destroy_all',as:'destroy_all_task'
  delete '/destroy_tags/:id' => 'tasks#destroy_tags' ,as:'destroy_tags'
  
  get '/challenge' => 'challenges#new',as:'new_challenge'
  patch '/complete_all_challenges' => 'challenges#complete_all',as:'complete_all_challenge'
  delete '/destroy_all_challenges' => 'challenges#destroy_all',as:'destroy_all_challenge'
  patch '/complete_challenges/:id' => 'challenges#complete',as:'complete_challenge'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
 
 has_many :tasks,dependent: :destroy
 belongs_to :user
 
 validates :name, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
   @user = User.find(current_user.id)
   @lists = @user.lists
  end

  def new
   @list = List.new
  end
  
  def create
   @list = List.new(list_params)
   @list.user_id = current_user.id
   if @list.save
    redirect_to lists_path
   else
    render :new
   end
  end
  
  def destroy
   list = List.find(params[:id])
   if list.user_id == current_user.id
    list.destroy
    redirect_to lists_path
   else
    redirect_to user_path(current_user.id)
   end
  end
  
  private
  
  def list_params
   params.require(:list).permit(:name)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/index.html.erb
<div class="container">
 <div class="row m-5">
  <h5 class="box box-text rounded-pill mt-5 p-3">リスト一覧</h5>
 </div>
 
 <div class="row justify-content-center">
  <table class="table box box-text rounded table-borderless col-lg-6 col-12">
   <thead class="border-bottom">
    <tr>
     <th class="text-center"><%= link_to "+  リストを追加する",new_list_path,class:'btn-sm btn-outline-primary' %></th>
     <th colspan="2">未完了</th>
    </tr>
   </thead>
   <tbody>
    <% @lists.each do |list| %>
     <tr>
      <td class="text-center">
       <%= link_to index_tasks_path(list.id),class:'btn-sm btn-outline-info' do %>
        <%= list.name %>
       <% end %>
      </td>
      <td class="text-center"><%= list.tasks.where(complete: false).count %></td>
      <td>
       <%= link_to list_path(list.id),method: :delete do %>
        <i class="fa-solid fa-trash-can garbage"></i>
       <% end %>
      </td>
     </tr>
    <% end %>
   </tbody>
  </table>
 </div>
</div>

app/views/lists/new.html.erb
<div class="container">
 <div class="row">
  <% if @list.errors.any? %>
   <ul class="box border border-danger p-5 mt-5">
    <% @list.errors.full_messages.each do |message| %>
     <li class="text-danger" style="list-style: none;"><%= message %></li>
    <% end %>
   </ul>
  <% end %>
 </div>
 
 <div class="row m-5">
  <h5 class="box box-text rounded p-3 m-5">リストを追加する</h5>
 </div>
 
 <div class="row justify-content-center">
  <%= form_with model: @list,url: lists_path do |f| %>
   <div class="form m-2">
    <%= f.text_field :name,class:'form-control text-center',:placeholder=> "リスト名　例:仕事" %>
   </div>
   
   <div class="text-center m-2">
    <%= f.submit "追加する",class:'btn btn-success' %>
   </div>
  <% end %>
 </div>
</div>