config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  root to: "homes#top"
  resources :users,only:[:show,:edit,:update]
  resources :lists,only:[:index,:create,:destroy]
  resources :tasks,only:[:create,:edit,:update,:destroy]
  resources :challenges,only:[:index,:create,:destroy]
  resources :rewards,only:[:create,:update,:destroy]
  
  patch '/users/:id/withdrawal' => 'users#withdrawal',as:'withdrawal_user'
  
  get '/list' => 'lists#new',as:'new_list'
  
  get '/task/calendar' => 'tasks#calendar',as:'calendar_task'
  get '/task' => 'tasks#new',as:'new_task'
  get '/tasks/:id' => 'tasks#index',as:'index_tasks'
  patch '/complete_all_tasks/:id' => 'tasks#complete_all',as:'complete_all_task'
  patch '/complete_tasks/:id' => 'tasks#complete',as:'complete_task'
  delete '/destroy_all_tasks/:id' => 'tasks#destroy_all',as:'destroy_all_task'
  delete '/destroy_tags/:id' => 'tasks#destroy_tags' ,as:'destroy_tags'
  
  get '/challenge' => 'challenges#new',as:'new_challenge'
  patch '/complete_all_challenges' => 'challenges#complete_all',as:'complete_all_challenge'
  delete '/destroy_all_challenges' => 'challenges#destroy_all',as:'destroy_all_challenge'
  patch '/complete_challenges/:id' => 'challenges#complete',as:'complete_challenge'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord

 belongs_to :list
 belongs_to :user
 
 has_many :tag_maps,dependent: :destroy
 has_many :tags,through: :tag_maps
 
 validates :name, presence: true
 
 def save_tag(sent_tags)
  current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
  old_tags = current_tags - sent_tags
  new_tags = sent_tags - current_tags
  
  old_tags.each do |old|
   self.tags.delete Tag.find_by(tag_name: old)
  end
    
  new_tags.each do |new|
   new_task_tag = Tag.find_or_create_by(tag_name: new)
   self.tags << new_task_tag
  end
 end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
   @list = List.find(params[:id])
   @task = current_user.tasks
   @list_tasks = @list.tasks
   @task.each do |task|
    @tags = task.tags
   end
   @tasks = params[:tag_id].present? ? Tag.find(params[:tag_id]).tasks : @list_tasks.order(params[:sort])
  end

  def new
   @task = Task.new
   @list = current_user.lists
  end
  
  def calendar
   @events = current_user.tasks
  end
  
  def create
   @task = Task.new(task_params)
   @list = current_user.lists
   @task.user_id = current_user.id
   tag_list = params[:task][:tag_name].split(nil)
   if @task.save
    @task.save_tag(tag_list)
    redirect_to index_tasks_path(@task.list_id)
   else
    render :new
   end
  end

  def edit
   @task = Task.find(params[:id])
   @task_tags = @task.tags
  end
  
  def update
   @task = Task.find(params[:id])
   tag_list = params[:task][:tag_name].split(nil)
   @task.update(task_params)
   @task.save_tag(tag_list)
   redirect_to index_tasks_path(@task.list_id)
  end
  
  def destroy
   @task = Task.find(params[:id])
   if @task.user_id == current_user.id
    @task.destroy
    redirect_to index_tasks_path(@task.list_id)
   else
    redirect_to user_path(current_user.id)
   end
  end
  
  def destroy_all
   @list = List.find(params[:id])
   @tasks = @list.tasks
   @tasks.each do |task|
    if task.complete
     task.destroy
    end
   end
   redirect_to index_tasks_path(@list.id)
  end
  
  def destroy_tags
   @task = Task.find(params[:id])
   @task_tags = @task.tags
   @task_tags.destroy_all
   redirect_to edit_task_path(@task.id)
  end
  
  def complete
   @task = Task.find(params[:id])
   if @task.complete
    @task.update(complete: false)
   else
    @task.update(complete: true)
   end
   redirect_to index_tasks_path(@task.list_id)
  end
  
  def complete_all
   @list = List.find(params[:id])
   @tasks = @list.tasks
   @tasks.update_all(complete: true)
   redirect_to index_tasks_path(@list.id)
  end
  
  private
  
  def task_params
   params.require(:task).permit(:name,:explanation,:tag,:start_time,:finish_time,:list_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/calendar.html.erb
<div>
 <%= month_calendar events: @events do |date,events| %>
  <%= date.day %>
  
  <% events.first(3).each do |event| %>
   <div>
    <%= link_to edit_task_path(event.id) do %>
     <%= event.name %>(<%= event.start_time.strftime('%H:%M') %>~<%= event.finish_time.strftime('%H:%M') %>)
    <% end %>
   </div>
  <% end %>
 <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="container">
 <div class="row justify-content-center m-5">
  <%= form_with model: @task,url: task_path(@task.id),method: :patch do |f| %>
   
   <div class="form m-2">
    <%= f.text_field :name,class:'form-control text-center' %>
   </div>
   
   <div class="form form-box box-text m-2 text-center">
    <%= f.label :explanation,"MEMO" %>
    <%= f.text_area :explanation,class:'form-control',size:"60x10" %>
   </div>
   
   <div class="form form-box box-text m-2">
    <% @task_tags.each do |tag| %>
     #<%= tag.tag_name %>
    <% end %>
   </div>
   
   <div class="form text-center m-2">
    <%= f.text_field :tag_name,class:'form-box box-text text-center',:placeholder=> "タグを追加" %></br>
    <%= link_to "空にする",destroy_tags_path(@task.id),method: :delete,class:'btn-sm btn-danger' %>
    <p>タグを複数追加する場合は半角スペースで間を開けてください</p>
   </div>
   
   <div class="time text-center">
    <%= f.datetime_field :start_time,class:'form-box box-text' %> ~ 
    <%= f.datetime_field :finish_time,class:'form-box box-text' %>
   </div>
   
   <div class="text-center m-5">
    <%= f.submit "変更内容を確定する",class:'btn btn-success' %>
   </div>
  <% end %>
 </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
 <div class="row m-5">
  <%= form_with url: index_tasks_path(@list.id),method: :get,class: 'boards_searchForm' do |f| %>
   <%= f.select :tag_id,options_from_collection_for_select(@tags, :id, :tag_name, params[:tag_id]),{prompt: 'タグで絞り込み検索'},{onchange: 'submit(this.form)',class:'form-control'} %>
  <% end %>
  <%= link_to "+",new_task_path,class:'btn btn-success rounded-circle p-0 ml-auto mr-5',style:"width: 4rem; height: 4rem; line-height: 4rem; font-size: 30px;" %>
 </div>
 
 <div class="form-inline">
  <table class="table table-borderless box box-text text-center col-lg-3 mr-4">
   <thead class="border-bottom">
    <tr>
     <th>完了リスト</th>
     <th><%= link_to "全て削除",destroy_all_task_path(@list.id),method: :delete,class:'btn-sm btn-danger' %></th>
    </tr>
   </thead>
   <tbody>
    <% @tasks.each do |task| %>
     <% if task.complete %>
      <tr>
       <td>
        <%= link_to edit_task_path(task.id),class:'btn-sm btn-outline-info' do %>
         <%= task.name %>
        <% end %>
       </td>
       <td><%= link_to "戻す",complete_task_path(task.id),method: :patch,class:'btn-sm btn-outline-danger' %></td>
      </tr>
     <% end %>
    <% end %>
   </tbody>
  </table>
  
  <table class="table table-borderless box box-text col-lg-8 ml-5">
   <thead class="border-bottom">
    <tr>
     <th class="form-cell" colspan="2"><%= @list.name %></th>
     <th colspan="2">
      名前順<%= link_to "↑",index_tasks_path(@list.id,sort: 'name') %><%= link_to "↓",index_tasks_path(@list.id,sort: 'name DESC') %>
      作成順<%= link_to "↑",index_tasks_path(@list.id,sort: 'created_at') %><%= link_to "↓",index_tasks_path(@list.id,sort: 'created_at DESC') %>
      日付順<%= link_to "↑",index_tasks_path(@list.id,sort: 'start_time') %><%= link_to "↓",index_tasks_path(@list.id,sort: 'start_time DESC') %>
     </th>
    </tr>
   </thead>
   <tbody>
    <% @tasks.each do |task| %>
     <% if task.user_id == current_user.id %>
      <% unless task.complete %>
       <tr>
        <td>
         <%= link_to complete_task_path(task.id),method: :patch do %>
          <i class="fa-solid fa-check fa-lg"></i>
         <% end %>
        </td>
        <td>
         <%= link_to edit_task_path(task.id),class:'btn-sm btn-outline-info' do %>
          <%= task.name %>
         <% end %>
        </td>
        <td><%= task.start_time.strftime('%Y.%m.%d') %></td>
        <td>
         <%= link_to task_path(task.id),method: :delete do %>
          <i class="fa-solid fa-trash-can garbage"></i>
         <% end %>
        </td>
       </tr>
      <% end %>
     <% end %>
    <% end %>
    <tr>
     <td colspan="4" class="text-center"><%= link_to "全て完了",complete_all_task_path(@list.id),method: :patch,class:'btn btn-success' %></td>
    </tr>
   </tbody>
  </table>
 </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
 <div class="row">
  <% if @task.errors.any? %>
   <ul class="box border border-danger p-5 mt-5">
    <% @task.errors.full_messages.each do |message| %>
     <li class="text-danger" style="list-style: none;"><%= message %></li>
    <% end %>
   </ul>
  <% end %>
 </div>
 
 <div class="row mt-5">
  <h5 class="box box-text rounded p-3 mt-5">タスクを追加する</h5>
 </div>
 
 <div class="row justify-content-center">
  <%= form_with model: @task,url: tasks_path do |f| %>
   <div class="form m-2">
    <%= f.select :list_id, @list.map{|list| [list.name,list.id]},{include_blank: "--リストを選択--"},{class:'form-control text-center'} %>
   </div>
   
   <div class="form m-2">
    <%= f.text_field :name,class:'form-control text-center',:placeholder=> "何をしますか？　例:会議" %>
   </div>
   
   <div class="form form-box box-text m-2 text-center">
    <%= f.label :explanation, "MEMO" %>
    <%= f.text_area :explanation,class:'form-control',size:"40x5" %>
   </div>
   
   <div class="form text-center m-2">
    <%= f.text_field :tag_name,class:'form-box box-text text-center',:placeholder=> "タグを追加" %>
    <p>タグを複数追加する場合は半角スペースで間を開けてください</p>
   </div>
   
   <div class="time text-center">
    <%= f.datetime_field :start_time,value: Time.current.strftime('%Y-%m-%dT00:00:00'),class:'form-box' %>
    <%= f.datetime_field :finish_time,value: Time.current.strftime('%Y-%m-%dT00:00:00'),class:'form-box' %>
   </div>
   
   <div class="text-center m-5">
    <%= f.submit "追加する",class:'btn btn-success' %>
   </div>
  <% end %>
 </div>
</div>