config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  root to: "homes#top"
  resources :users,only:[:show,:edit,:update]
  resources :lists,only:[:index,:create,:destroy]
  resources :tasks,only:[:create,:edit,:update,:destroy]
  resources :challenges,only:[:index,:create,:destroy]
  resources :rewards,only:[:create,:update,:destroy]
  
  patch '/users/:id/withdrawal' => 'users#withdrawal',as:'withdrawal_user'
  
  get '/list' => 'lists#new',as:'new_list'
  
  get '/task/calendar' => 'tasks#calendar',as:'calendar_task'
  get '/task' => 'tasks#new',as:'new_task'
  get '/tasks/:id' => 'tasks#index',as:'index_tasks'
  patch '/complete_all_tasks/:id' => 'tasks#complete_all',as:'complete_all_task'
  patch '/complete_tasks/:id' => 'tasks#complete',as:'complete_task'
  delete '/destroy_all_tasks/:id' => 'tasks#destroy_all',as:'destroy_all_task'
  delete '/destroy_tags/:id' => 'tasks#destroy_tags' ,as:'destroy_tags'
  
  get '/challenge' => 'challenges#new',as:'new_challenge'
  patch '/complete_all_challenges' => 'challenges#complete_all',as:'complete_all_challenge'
  delete '/destroy_all_challenges' => 'challenges#destroy_all',as:'destroy_all_challenge'
  patch '/complete_challenges/:id' => 'challenges#complete',as:'complete_challenge'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :lists,dependent: :destroy
  has_many :tasks,dependent: :destroy
  has_many :challenges,dependent: :destroy
  has_many :rewards,dependent: :destroy
  
  validates :total_point, numericality:{greater_than_or_equal_to: 0}
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
 before_action :sign_up_state,only:[:create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
     @user = current_user
     @user.lists.create(name: "このサイトの使い方",user_id: @user.id)
     @user.lists.each do |list|
      list.tasks.create([
       {list_id: list.id,
        user_id: @user.id,
        name: "タスクを追加する",
        explanation: "・マイページの「タスクを追加する」ボタンかタスク一覧画面の「＋」ボタンをクリックするとタスクの新規登録画面に移動します。
・一覧画面のチェックマークをクリックするとタスクが完了します。",
        start_time: Time.current,
        finish_time: Time.current},
       {
        list_id: list.id,
        user_id: @user.id,
        name: "タスク新規作成時の各項目について",
        explanation: "リストを選択: リストを設定することでタスクを分類できます。
タスク名: タスクの名前、タイトルを設定できます。
MEMO: 簡単なメモが書けます。
タグ: タグを設定することでタグを検索して目的のタスクが見つけやすくなります。
時間の設定: 開始日時、終了日時を設定してカレンダーに反映します。",
        start_time: Time.current,
        finish_time: Time.current
       },
       {
        list_id: list.id,
        user_id: @user.id,
        name: "チャレンジについて",
        explanation: "・チャレンジでは日々の習慣や毎日の目標などを設定し、達成することでポイントを貯められます。
・ポイントを消費して自分で設定した「ご褒美」が貰えます。",
        start_time: Time.current,
        finish_time: Time.current
       }])
     end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  
  def sign_up_state
   if @user = User.find_by(email: params[:user][:email])
    redirect_to new_user_registration_path,alert: '登録済みのユーザーです。'
   else
    return if !@user
   end
  end
   

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :user_state,only:[:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  
  def user_state
  @user = User.find_by(email: params[:user][:email])
  return if !@user
   if @user.valid_password?(params[:user][:password]) && !@user.is_deleted?
   else
   redirect_to root_path,alert: '退会済みのユーザーです'
   end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :self_user
 
  def show
   @user = User.find(params[:id])
   @tasks = @user.tasks.order(start_time: :desc)
   @task = @tasks.where(start_time: Time.zone.now.all_day)
  end

  def edit
   @user = User.find(params[:id])
  end
  
  def update
   @user = User.find(params[:id])
   @user.update(user_params)
   redirect_to user_path(@user.id)
  end
  
  def withdrawal
   @user = User.find(params[:id])
   @user.update(is_deleted: true)
   reset_session
   redirect_to root_path
  end
  
  private
  
  def user_params
   params.require(:user).permit(:name,:email)
  end
  
  def self_user
   @user = User.find(params[:id])
   unless @user == current_user
    redirect_to user_path(current_user.id)
   end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <h5 class="box box-text rounded-pill mt-5 p-3">ユーザー情報編集</h5>
 </div>
 
 <div class="row">
  <div class="form mx-auto">
   <%= form_with model: @user,url: user_path(@user.id),method: :patch do |f| %>
    <table class="table table-borderless mt-5 text-center mx-auto">
     <tbody>
      <tr>
       <td class="form-cell" align="center"><p class="title-text box-text rounded-pill p-1">名前</p></td>
       <td class="form-cell" colspan="2"><%= f.text_field :name,size:"30",class:'form-control' %></td>
      </tr>
      <tr>
       <td class="form-cell"><p class="title-text box-text rounded-pill p-1">メールアドレス</p></td>
       <td class="form-cell" colspan="2"><%= f.email_field :email,size:"30",class:'form-control' %></td>
      </tr>
      <tr>
       <td class="form-cell"></td>
       <td class="form-cell"><%= f.submit "変更する",class:'btn btn-success' %></td>
       <td class="form-cell"><%= link_to "退会する",withdrawal_user_path(@user.id),method: :patch,"data-confirm" => "本当に退会しますか？",class:'btn btn-danger' %></td>
      </tr>
     </tbody>
    </table>
   <% end %>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
  <div class="box rounded p-4 mt-5">
   <p class="box-text text-center">ユーザー</p>
   <table class="table table-borderless">
    <tbody>
     <tr>
      <td>名前</td>
      <td><%= @user.name %></td>
     </tr>
     <tr>
      <td>メールアドレス</td>
      <td><%= @user.email %></td>
     </tr>
    </tbody>
   </table>
   <p class="text-center">
    <%= link_to "編集する",edit_user_path(@user.id),class:'btn btn-success' %>
   </p>
  </div>
  
  <div class="box rounded-pill p-4 m-5 col-11 col-lg-7 ml-auto">
   <p class="box-text text-center px-5"><%= Date.current.strftime('%m月 %d日') %></p>
   <table class="table table-borderless text-center">
    <tbody>
     <% @task.each do |task| %>
      <% if task.complete %>
       <tr class="info border-bottom">
        <td>
         <%= link_to index_tasks_path(task.list_id),class:'btn-sm btn-outline-info' do %>
          <%= task.list.name %>
         <% end %>
        </td>
        <td><i class="fa-solid fa-check"><%= task.name %></i></td>
       </tr>
      <% else %>
       <tr class="border-bottom">
        <td class="text-right">
         <%= link_to index_tasks_path(task.list_id),class:'btn-sm btn-outline-info' do %>
          <%= task.list.name %>
         <% end %>
         </td>
        <td><%= task.name %></td>
       </tr>
      <% end %>
     <% end %>
     <% if @task.blank? %>
      <tr>
       <td>今日の予定はありません</td>
      </tr>
     <% end %>
    </tbody>
   </table>
   <p class="text-center">
    <%= link_to "+ タスクを追加する",new_task_path,class:'btn btn-primary' %>
   </p>
  </div>
 </div>
  
 <div class="row">
  <div class="box rounded-pill p-4 m-5 col-11 col-lg-7 ml-auto">
   <p class=" box-text text-center px-5">お知らせ</p>
   <table class="table table-borderless text-center">
    <tbody>
     <% @tasks.first(4).each do |task| %>
      <% if task.start_time <= Time.current %>
       <tr class="info border-bottom">
        <td><%= task.start_time.strftime('%H時%M分') %>:「<%= task.name %>」の開始時間です。</td>
       </tr>
      <% elsif task.finish_time >= Time.current %>
       <tr class="text-danger border-bottom">
        <td><%= task.finish_time.strftime('%H時%M分') %>:「<%= task.name %>」の終了時間です。</td>
       </tr>
      <% end %>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>