config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  root to: "homes#top"
  resources :users,only:[:show,:edit,:update]
  resources :lists,only:[:index,:create,:destroy]
  resources :tasks,only:[:create,:edit,:update,:destroy]
  resources :challenges,only:[:index,:create,:destroy]
  resources :rewards,only:[:create,:update,:destroy]
  
  patch '/users/:id/withdrawal' => 'users#withdrawal',as:'withdrawal_user'
  
  get '/list' => 'lists#new',as:'new_list'
  
  get '/task/calendar' => 'tasks#calendar',as:'calendar_task'
  get '/task' => 'tasks#new',as:'new_task'
  get '/tasks/:id' => 'tasks#index',as:'index_tasks'
  patch '/complete_all_tasks/:id' => 'tasks#complete_all',as:'complete_all_task'
  patch '/complete_tasks/:id' => 'tasks#complete',as:'complete_task'
  delete '/destroy_all_tasks/:id' => 'tasks#destroy_all',as:'destroy_all_task'
  delete '/destroy_tags/:id' => 'tasks#destroy_tags' ,as:'destroy_tags'
  
  get '/challenge' => 'challenges#new',as:'new_challenge'
  patch '/complete_all_challenges' => 'challenges#complete_all',as:'complete_all_challenge'
  delete '/destroy_all_challenges' => 'challenges#destroy_all',as:'destroy_all_challenge'
  patch '/complete_challenges/:id' => 'challenges#complete',as:'complete_challenge'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord
 
 belongs_to :user
 
 validates :name, presence: true
 validates :point,presence: true
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def new
   @challenge = Challenge.new
  end
  
  def index
   @user = User.find(current_user.id)
   @challenges = @user.challenges
   @reward = Reward.new
   @rewards = @user.rewards
  end

  def create
   @challenge = Challenge.new(challenge_params)
   @challenge.user_id = current_user.id
   if @challenge.save
    redirect_to challenges_path
   else
    render :new
   end
  end
  
  def complete
   @user = User.find(current_user.id)
   @challenge = Challenge.find(params[:id])
   if @challenge.complete
    @challenge.update(complete: false)
   else
    @user.total_point += @challenge.point
    @challenge.update(complete: true)
    @user.update(total_point: @user.total_point)
   end
   redirect_to challenges_path
  end
  
  def complete_all
   @user = User.find(current_user.id)
   @challenges = @user.challenges
   @challenges.each do |challenge|
    @user.total_point += challenge.point
   end
   @challenges.update_all(complete: true)
   @user.update(total_point: @user.total_point)
   redirect_to challenges_path
  end

  def destroy
   @challenge = Challenge.find(params[:id])
   @challenge.destroy
   redirect_to challenges_path
  end
  
  def destroy_all
   @challenges = current_user.challenges
   @challenges.each do |challenge|
    if challenge.complete
     challenge.destroy
    end
   end
   redirect_to challenges_path
  end
  
  private
  
  def challenge_params
   params.require(:challenge).permit(:name,:point)
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/index.html.erb
<div class="container">
 <div class="row">
  <% if @reward.errors.any? %>
   <ul class="box border border-danger p-5 mt-5">
    <% @reward.errors.full_messages.each do |message| %>
     <li class="text-danger" style="list-style: none;"><%= message %></li>
    <% end %>
   </ul>
  <% end %>
 </div>
 
 <div class="row point ml-auto col-5 mt-3">
  <p class="box box-text rounded-pill text-center py-2 m-auto col-lg-6"><%= @user.total_point %>P</p>
 </div>
  
 <div class="row">
  <div class="col-lg-6">
   <table class="table table-borderless box mt-5">
    <thead>
     <tr class="border-bottom">
      <th colspan="4"><%= link_to "+  チャレンジを追加する",new_challenge_path %></th>
     </tr>
    </thead>
   
    <tbody>
     <% @challenges.each do |challenge| %>
      <% unless challenge.complete %>
       <tr>
        <td>
         <%= link_to complete_challenge_path(challenge.id),method: :patch do %>
          <i class="fa-solid fa-check fa-lg"></i>
         <% end %>
        </td>
        <td><%= challenge.name %></td>
        <td><%= challenge.point %>P</td>
        <td>
         <%= link_to challenge_path(challenge.id),method: :delete do %>
          <i class="fa-solid fa-trash-can garbage"></i>
         <% end %>
        </td>
       </tr>
      <% end %>
     <% end %>
     <tr class="border border-white text-center">
      <td colspan="4"><%= link_to "全て完了",complete_all_challenge_path,method: :patch,class:'btn-sm btn-success' %></td>
     </tr>
    </tbody>
   </table>
  </div>
  
  <div class="col-lg-6 text-center mx-auto justify-content-center">
   <table class="table table-borderless box mt-5">
    <thead>
     <tr class="border-bottom">
      <th colspan="4" class="box-text text-center col-4">ご褒美リスト</th>
     </tr>
    </thead>
    
    <tbody>
     <% @rewards.each do |reward| %>
      <tr>
       <td>
        <%= link_to reward_path(reward.id),method: :patch do %>
         <i class="fa-solid fa-check fa-lg"></i>
        <% end %>
       </td>
       <td><%= reward.cost_point %>P</td>
       <td><%= reward.reward_name %></td>
       <td>
        <%= link_to reward_path(reward.id),method: :delete do %>
         <i class="fa-solid fa-trash-can garbage"></i>
        <% end %>
       </td>
      </tr>
     <% end %>
    </tbody>
   </table>
   
   <%= form_with model: @reward,url: rewards_path,method: :post do |f| %>
    <div class="form">
     <%= f.text_field :reward_name,style:'background-color: #FFFFCC; border: 2px solid #FFCC00;',:placeholder=> "ご褒美名　例:ゲーム" %></br>
     <%= f.select :cost_point, {'ご褒美小(100p)':100,'ご褒美中(150p)':150,'ご褒美大(200p)':200},{include_blank: "消費ポイント"},{class:'m-2',style:'background-color: #FFFFCC; border: 2px solid #FFCC00;'} %>
     <%= f.submit "追加",class:'btn-sm btn-success' %>
    </div>
   <% end %>
  </div>
 </div>
 
 <div class="row">
  <table class="table table-borderless box col-lg-6 mt-5">
   <thead>
    <tr class="border-bottom">
     <th class="box-text">完了したチャレンジ</th>
     <th><%= link_to "全て削除",destroy_all_challenge_path,method: :delete,class:'btn-sm btn-danger' %></th>
    </tr>
   </thead>
   
   <tbody>
    <% @challenges.first(5).each do |challenge| %>
     <% if challenge.complete %>
      <tr>
       <td><%= challenge.name %></td>
       <td><%= link_to "チャレンジする",complete_challenge_path(challenge.id),method: :patch,class:'btn-sm btn-success' %></td>
      </tr>
     <% end %>
    <% end %>
   </tbody>
  </table>
 </div>
</div>

app/views/challenges/new.html.erb
<div class="container">
 <div class="row">
  <% if @challenge.errors.any? %>
   <ul class="box border border-danger p-5 mt-5">
    <% @challenge.errors.full_messages.each do |message| %>
     <li class="text-danger" style="list-style: none;"><%= message %></li>
    <% end %>
   </ul>
  <% end %>
 </div>
 
 <div class="row m-5">
  <h5 class="box box-text rounded mt-5 p-3">チャレンジを追加する</h5>
 </div>
 
 <div class="row justify-content-center">
  <%= form_with model: @challenge,url: challenges_path,method: :post do |f| %>
   <div class="form m-2">
    <%= f.text_field :name,class:'form-control',size:"30",:placeholder=> "チャレンジ名　例:ランニング" %>
   </div>
   
   <div class="form m-2">
    <%= f.select :point, {'EASY(50p)':50,'NORMAL(100p)':100,'HARD(150p)':150},{include_blank: "難易度"},{class:'form-control'} %>
   </div>
   
   <div class="text-center">
    <%= f.submit "追加する",class:'btn btn-success' %>
   </div>
  <% end %>
 </div>
</div>